package beans;
// Generated 14 janv. 2019 22:36:27 by Hibernate Tools 4.3.1
/**
 * Cancerpredict generated by hbm2java
 */
public class Cancerpredict  implements java.io.Serializable {


     private int id;
     private String statutSocial;
     private String contry;
     private String lieuResidence;
     private String statutFumeur;
     private String statutMarital;
     private String sexe;
     private String classeDage;
     private String typeCancer;

    public Cancerpredict() {
    }

	
    public Cancerpredict(int id) {
        this.id = id;
    }
    public Cancerpredict(int id, String statutSocial, String contry, String lieuResidence, String statutFumeur, String statutMarital, String sexe, String classeDage, String typeCancer) {
       this.id = id;
       this.statutSocial = statutSocial;
       this.contry = contry;
       this.lieuResidence = lieuResidence;
       this.statutFumeur = statutFumeur;
       this.statutMarital = statutMarital;
       this.sexe = sexe;
       this.classeDage = classeDage;
       this.typeCancer = typeCancer;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getStatutSocial() {
        return this.statutSocial;
    }
    
    public void setStatutSocial(String statutSocial) {
        this.statutSocial = statutSocial;
    }
    public String getContry() {
        return this.contry;
    }
    
    public void setContry(String contry) {
        this.contry = contry;
    }
    public String getLieuResidence() {
        return this.lieuResidence;
    }
    
    public void setLieuResidence(String lieuResidence) {
        this.lieuResidence = lieuResidence;
    }
    public String getStatutFumeur() {
        return this.statutFumeur;
    }
    
    public void setStatutFumeur(String statutFumeur) {
        this.statutFumeur = statutFumeur;
    }
    public String getStatutMarital() {
        return this.statutMarital;
    }
    
    public void setStatutMarital(String statutMarital) {
        this.statutMarital = statutMarital;
    }
    public String getSexe() {
        return this.sexe;
    }
    
    public void setSexe(String sexe) {
        this.sexe = sexe;
    }
    public String getClasseDage() {
        return this.classeDage;
    }
    
    public void setClasseDage(String classeDage) {
        this.classeDage = classeDage;
    }
    public String getTypeCancer() {
        return this.typeCancer;
    }
    
    public void setTypeCancer(String typeCancer) {
        this.typeCancer = typeCancer;
    }
}


