package beans;
// Generated 3 janv. 2019 01:39:04 by Hibernate Tools 4.3.1



/**
 * Test generated by hbm2java
 */
public class Test  implements java.io.Serializable {


     private Integer id;
     private String n;
     private String p;

    public Test() {
    }

    public Test(String n, String p) {
       this.n = n;
       this.p = p;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getN() {
        return this.n;
    }
    
    public void setN(String n) {
        this.n = n;
    }
    public String getP() {
        return this.p;
    }
    
    public void setP(String p) {
        this.p = p;
    }




}


